### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by Paku-** [positronic57/DS18S20Library#1]
Hi, 

Could you please public some samples ?
Just simeple one pass temperature reading would be nice :)

**Comment by positronic57** [comment]
Hi,

The example is added in the repo.

Cheers.

**Comment by Paku-** [comment]
Thanks :)

**Comment by Paku-** [comment]
Hi @positronic57,

It's me again.

Could not build source as here:
````
	if (ReadDS18S20ScratchPad(scratchpad))
	{
		// Send the value of the temperature registers over serial port
		USART_SendString("Current Temperature is:");
		ConvertTemperature2String(scratchpad[1],scratchpad[0]);
	}
````
ConvertTemperature2String()  function is undefined.
````
main.c: undefined reference to `ConvertTemperature2String'
````
and a little cosmetic isssue is on char-uint8 conversion

````
../DS18S20/main.c:60:2: warning: pointer targets in passing argument 1 of 'ReadDS18S20ScratchPad' differ in signedness [-Wpointer-sign]
````

Paku

**Comment by positronic57** [comment]
Missing function is added to the example.

**Comment by Paku-** [comment]
Hi,
What framework do you use for build winAVR or Atmel ??
There are still some headers issues for Atmel framework.

**Comment by positronic57** [comment]
Example has been updated so it can be build with Atmel Studio 6.2.

**Comment by Paku-** [comment]
I am sorry but finally I used dallas_one_wire library from Mike Roddewig... I just was not able to make yours working. Building was not a problem. In the mean time have got much more experience on using the OW interface so maybe will try again later. Thanks for support anyway.

**Comment by Paku-** [comment]
fyi

https://github.com/Paku-/DS18B20DallasOneWire

**Comment by positronic57** [comment]
Hi,
Thanks for the link, I will have a look.
Regarding your failed attempt to make my example working, what kind of issue did you face? I tested the code on ATtiny2313 and it worked without issues. Did you set the F_CPU symbol which is used by the functions for time delay? I checked and Atmel Studio doesn't define it by default. It should have the value of the CPU freq expressed as long int. Also did you update the config.h to match your hardware config?

Thanks

**Comment by Paku-** [comment]
Yes all was done, I have spent a lot of time on it. Could be it was a timing issue for my 1Wire hardware/bus. The problem I could not find/solve that time. Now know more so will try again later.
You may consider including some basic bus test at the beginning so someone new to the subject will get any message on start for the first time (like "got answer from slave on reset"). I was not able to get any reaction from bus and, as had no experience, had to move to some more documented code.
